apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello
          image: nigelpoulton/pluralsight-docker-ci:latest
          ports:
          - containerPort: 8080
