version: "3"

services:
    front-end-service:
      image: ivanspasov/vue-js-front-end:latest
      ports:
        - 8080:80
      depends_on:
        - product-service

    db:
      container_name: postgres
      image: postgres
      environment:
        POSTGRES_HOST: postgres
        POSTGRES_PASSWORD: 123456
        POSTGRES_USERNAME: postgres
      #volumes:
        #- ./postgres-data:/var/lib/postgresql/data
      ports:
      - 5432:5432

    product-service:
      image: ivanspasov/springbootapi:latest
      ports:
        # how to access back end api without exposing it on port, axios??
        - 9000:9000
      depends_on:
        - db

