apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: front-end-service
  name: front-end-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: front-end-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: front-end-service
    spec:
      containers:
      - image: ivanspasov/vue-js-front-end:latest
        imagePullPolicy: ""
        name: front-end-service
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
